apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coupon-manager
  template:
    metadata:
      labels:
        app: coupon-manager
    spec:
      containers:
        - name: coupon-manager
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080