apiVersion: v1
kind: Service
metadata:
  name: coupon-manager-service
  labels:
    app: coupon-manager
spec:
  selector:
    app: coupon-manager

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer