name: Deploy to ECR
on:
  push:
    branches: [ main ]
env:
  ECR_REPOSITORY: stickrepo
  EKS_CLUSTER_NAME: stickcluster
  AWS_REGION: us-east-2
  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  # Asegúrate de que esta variable esté definida
jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Check Kubernetes config
        run: |
          cat ~/.kube/config

      - name: Deploy to EKS
        env:
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          sed -i "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" deployment.yml && \
          kubectl apply -f deployment.yml --validate=false